---
- name: Configure Ansible
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Ensure /etc/ansible directory exists
      file:
        path: /etc/ansible
        state: directory
        mode: '0755'

    - name: Create ansible.cfg file
      copy:
        dest: /etc/ansible/ansible.cfg
        content: |
          [defaults]
          inventory = /etc/ansible/hosts
          remote_user = {{ ansible_user | default('your_default_user') }}
          host_key_checking = False
          retry_files_enabled = False
          
          [privilege_escalation]
          become = True
          become_method = sudo
          become_user = root
          become_ask_pass = False
          
          [ssh_connection]
          pipelining = True
          control_path = /tmp/ansible-ssh-%%h-%%p-%%r
        mode: '0644'

    - name: Ensure inventory file exists
      copy:
        content: |
          [local]
          localhost ansible_connection=local
          
          # Add your other hosts here
          # [webservers]
          # web01 ansible_host=192.168.1.101
          # web02 ansible_host=192.168.1.102
        dest: /etc/ansible/hosts
        force: no  # Ne pas écraser s'il existe déjà
