---
- name: Créer l'utilisateur Ansible sur tous les serveurs
  hosts: all
  become: yes
  vars:
    ansible_user_name: ansible
    ansible_user_password: "{{ vault_ansible_user_password }}"
    ansible_user_ssh_key: "{{ lookup('file', '~/.ssh/ansible_ed25519.pub') }}"

  tasks:
    - name: Créer l'utilisateur Ansible
      user:
        name: "{{ ansible_user_name }}"
        password: "{{ ansible_user_password | password_hash('sha512') }}"
        groups: sudo
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Configurer le sudo sans mot de passe pour l'utilisateur Ansible
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ ansible_user_name }}'
        line: '{{ ansible_user_name }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Ajouter la clé SSH pour l'utilisateur Ansible
      authorized_key:
        user: "{{ ansible_user_name }}"
        key: "{{ ansible_user_ssh_key }}"
        state: present

    - name: S'assurer que SSH autorise l'authentification par clé publique
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
      notify: Redémarrer SSH

  handlers:
    - name: Redémarrer SSH
      service:
        name: sshd
        state: restarted
