---
- hosts: srvr5
  become: yes

  vars:
    mysql_root_password: "root"
    db_name: "test"
    db_user: "user_test"
    db_password: "123"
    db_user_host: "localhost"

  tasks:
    - name: Check if Python 3 is installed
      command: python3 --version
      register: python_version
      ignore_errors: yes
      changed_when: false

    - name: Install Python 3
      apt:
        name: python3
        state: present
      when: python_version.rc != 0

    - name: Check if pip is installed
      command: pip3 --version
      register: pip_version
      ignore_errors: yes
      changed_when: false

    - name: Install pip
      apt:
        name: python3-pip
        state: present
      when: pip_version.rc != 0

    - name: Install PyMySQL
      pip:
        name: PyMySQL
        state: present
        
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Remove anonymous users
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create a new database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create a new user and grant all privileges on the database from specific subnet
      mysql_user:
        name: "{{ db_user }}"
        host: "{{ db_user_host }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        
    - name: Create a new user ADMIN and grant all root privileges
      mysql_user:
        name: "admin"
        host: "192.168.1.%"
        password: "admin"
        priv: "*.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Configure MySQL to listen on localhost and the specific network interface
      ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: bind-address
        value: "127.0.0.1,192.168.1.51"
      notify: Restart MySQL

    - name: Allow MySQL port in UFW
      ufw:
        rule: allow
        port: '3306'

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
